{{- if .Values.omni.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-preinstall"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ include "omni.chart" . }}"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: hook-succeeded
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "create"]
{{- end }}
